/*
ORACLE 12C alti surumler icin asagidaki gibi 4 adimda otomatik artan eklenir.
*/
-- 1) Once tablo create edilir
CREATE TABLE books (
  id         NUMBER(10)    NOT NULL,
  bookName   VARCHAR2(100) NOT NULL
);

-- 2) Primary Key alani belirtilir
ALTER TABLE books
  ADD (
    CONSTRAINT books_pk PRIMARY KEY (id)
  );
  
-- 3) sequence olusturulur
CREATE SEQUENCE books_sequence;


-- 4) Trigger eklenir
  CREATE OR REPLACE TRIGGER books_on_insert
  BEFORE INSERT ON books
  FOR EACH ROW
BEGIN
  SELECT books_sequence.nextval
  INTO :new.id
  FROM dual;
END;

-- deneme
insert into books(bookName) values('Kitap Ad');

/*
ORACLE 12C ustu surumler icin asagidaki sekilde otomatik artan eklenir.
*/

CREATE TABLE books (
  id         NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
  bookName   VARCHAR2(100) NOT NULL
);